# Generated by Django 2.2 on 2022-12-03 16:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, max_length=36, verbose_name='Город')),
                ('phone', models.CharField(blank=True, max_length=11, verbose_name='Номер телефона')),
                ('count_news', models.IntegerField(default=0, verbose_name='Количество опубликованных новостей')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('can_verify_user', 'Может верифицировать пользователя'), ('can_activate_news', 'Может активировать новость')),
            },
        ),
    ]
