# Generated by Django 2.2 on 2022-12-12 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'permissions': (('can_verify_user', 'Может верифицировать пользователя'), ('can_activate_news', 'Может активировать новость')), 'verbose_name': 'profile', 'verbose_name_plural': 'profiles'},
        ),
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(blank=True, max_length=36, verbose_name='city'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='count_news',
            field=models.IntegerField(default=0, verbose_name='count public news'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=11, verbose_name='phone'),
        ),
    ]
