# Generated by Django 2.2 on 2022-12-13 04:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_goods', '0005_offer_promotion'),
        ('app_users', '0003_profile_loyalty_program_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='loyalty_program_item',
        ),
        migrations.CreateModel(
            name='PersonalCabinet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.IntegerField(default=0, verbose_name='balance')),
                ('loyalty_program_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_goods.LoyaltyProgram', verbose_name='loyalty program item')),
                ('offer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_goods.Offer', verbose_name='offer')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app_users.Profile')),
            ],
            options={
                'verbose_name': 'personal cabinet',
                'verbose_name_plural': 'personal cabinets',
            },
        ),
    ]
