# Generated by Django 2.2 on 2022-12-18 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0004_auto_20221213_0720'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalcabinet',
            name='status_points',
            field=models.IntegerField(default=0, verbose_name='status'),
        ),
    ]
