# Generated by Django 2.2 on 2022-12-12 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_goods', '0003_loyaltyprogram'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loyaltyprogram',
            options={'verbose_name': 'loyalty program', 'verbose_name_plural': 'loyalty programs'},
        ),
    ]
