# Generated by Django 2.2 on 2022-12-12 04:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_records', '0002_auto_20221208_0421'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='record',
            options={'verbose_name': 'record', 'verbose_name_plural': 'records'},
        ),
        migrations.AlterField(
            model_name='record',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='author'),
        ),
        migrations.AlterField(
            model_name='record',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date create'),
        ),
        migrations.AlterField(
            model_name='record',
            name='text',
            field=models.TextField(verbose_name='text'),
        ),
    ]
