# Generated by Django 2.2 on 2022-12-12 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_media', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='file',
            options={'verbose_name': 'file', 'verbose_name_plural': 'files'},
        ),
    ]
