# Generated by Django 4.1.4 on 2022-12-21 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_housing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HousingObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='заголовок')),
                ('description', models.TextField(blank=True, default='', verbose_name='описание')),
            ],
            options={
                'verbose_name': 'жильё',
                'verbose_name_plural': 'жильё',
            },
        ),
        migrations.CreateModel(
            name='RoomsNumberInHousingObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='количество комнат')),
            ],
        ),
        migrations.AddField(
            model_name='housingtype',
            name='code',
            field=models.CharField(default=1, max_length=32, verbose_name='код'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Housing',
        ),
        migrations.DeleteModel(
            name='NumberOfRoomsInHousing',
        ),
        migrations.AddField(
            model_name='housingobject',
            name='rooms_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_housing.roomsnumberinhousingobject'),
        ),
        migrations.AddField(
            model_name='housingobject',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_housing.housingtype'),
        ),
    ]
