# Generated by Django 2.2 on 2022-12-16 10:57

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=32, verbose_name='имя')),
                ('last_name', models.CharField(max_length=64, verbose_name='фамилия')),
                ('year_of_birth', models.DateTimeField(verbose_name='дата рождения')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='название')),
                ('isbn', models.CharField(max_length=16, unique=True, verbose_name='международный стандартный книжный номер')),
                ('year_of_issue', models.DateTimeField(verbose_name='год выпуска')),
                ('number_of_pages', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='количество страниц')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_library.Author', verbose_name='автор')),
            ],
        ),
    ]
